[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"

# Configurar el directorio de trabajo
[variables]
NIXPACKS_PATH = "./backend"
