# Configuración optimizada para Railway con Nixpacks
[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --production=false --silent"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"

# Variables de entorno
[variables]
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NODE_ENV = "production"
