version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: control-financiero-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: control_financiero
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Backend API (NestJS)
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: control-financiero-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/control_financiero?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      CORS_ORIGIN: https://your-domain.com
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  # Frontend (Angular)
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: control-financiero-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
